ersion: 0.2

phases:
  pre_build:
    commands:
      - cd ./React/redux
      - npm install
  build:
    commands:
      - npm run build

artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: build